# Generated by Django 2.2.4 on 2020-11-27 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAttribute',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('attribute_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='案例属性id')),
                ('is_free_postage', models.IntegerField(verbose_name='是否包邮')),
                ('is_fast_refund', models.IntegerField(verbose_name='是否急速退款')),
                ('is_jd_self_manage', models.IntegerField(verbose_name='是否京东自营')),
                ('is_jd_logistics', models.IntegerField(verbose_name='是否京东物流')),
                ('is_jd_supermarket', models.IntegerField(verbose_name='是否京东超市')),
                ('is_jd_good_store', models.IntegerField(verbose_name='是否京东好店')),
                ('is_jd_tianmao_store', models.IntegerField(verbose_name='是否天猫商城商品')),
            ],
            options={
                'db_table': 'dz_case_attribute',
            },
        ),
        migrations.CreateModel(
            name='CaseComments',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('comment_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='案例评论id')),
                ('comment_people', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'dz_case_comment',
            },
        ),
        migrations.CreateModel(
            name='CaseDetailInfos',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('case_detail_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='详情页id')),
                ('old_place', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品原价')),
                ('monthly_salary', models.IntegerField(verbose_name='月销量')),
                ('comment_num', models.IntegerField(verbose_name='评论数')),
                ('brand_name', models.CharField(max_length=16, verbose_name='品牌名')),
                ('good_type', models.CharField(max_length=30, verbose_name='商品种类')),
                ('good_flavor', models.CharField(max_length=300, verbose_name='商品口味')),
                ('origin_place', models.CharField(max_length=30, verbose_name='产地')),
                ('factory_name', models.CharField(max_length=30, verbose_name='厂名')),
            ],
            options={
                'db_table': 'dz_case_detail_infos',
            },
        ),
        migrations.CreateModel(
            name='CaseInfos',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('case_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='案例id')),
                ('store_platform', models.CharField(max_length=50, verbose_name='店铺平台')),
                ('picture_url', models.URLField(verbose_name='案例图片')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='现价')),
                ('delivery_place', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='发货地')),
                ('payer_num', models.IntegerField(verbose_name='付款人数')),
                ('design_cycle', models.CharField(max_length=100, verbose_name='商品名')),
            ],
            options={
                'db_table': 'dz_case_info',
            },
        ),
        migrations.CreateModel(
            name='StepFlow',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('step_flow_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='步骤流程id')),
                ('step_picture', models.ImageField(upload_to='cases/stepflow/', verbose_name='流程轮播图图片')),
                ('index', models.IntegerField(verbose_name='轮播图的优先级')),
            ],
            options={
                'db_table': 'dz_step_flow',
            },
        ),
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('store_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='详情页id')),
                ('store_name', models.CharField(max_length=100, verbose_name='店铺名称')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cases.CaseInfos', verbose_name='案例')),
            ],
            options={
                'db_table': 'dz_store_info',
            },
        ),
        migrations.CreateModel(
            name='CaseRotionCard',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('rotion_card_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='案例轮播图id')),
                ('case_picture', models.ImageField(upload_to='cases/rotion/', verbose_name='案例轮播图图片')),
                ('index', models.IntegerField(verbose_name='轮播图的优先级')),
                ('url', models.URLField(verbose_name='轮播图锁指向的案例的url')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cases.CaseInfos', verbose_name='案例')),
            ],
            options={
                'db_table': 'dz_case_rotion_card',
            },
        ),
    ]
