# Generated by Django 2.2.4 on 2020-11-27 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseinfos',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.OrderInfo', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='casedetailinfos',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cases.CaseInfos', verbose_name='案例'),
        ),
        migrations.AddField(
            model_name='casecomments',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cases.CaseInfos', verbose_name='案例'),
        ),
        migrations.AddField(
            model_name='caseattribute',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cases.CaseInfos', verbose_name='案例'),
        ),
    ]
