# Generated by Django 2.2.4 on 2020-11-27 08:56

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20201127_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='casecomments',
            name='comment_content',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now, verbose_name='评论'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caseattribute',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='caseattribute',
            name='is_fast_refund',
            field=models.BooleanField(default=False, verbose_name='是否急速退款'),
        ),
        migrations.AlterField(
            model_name='caseattribute',
            name='is_free_postage',
            field=models.BooleanField(default=False, verbose_name='是否包邮'),
        ),
        migrations.AlterField(
            model_name='caseattribute',
            name='is_jd_good_store',
            field=models.BooleanField(default=False, verbose_name='是否京东好店'),
        ),
        migrations.AlterField(
            model_name='caseattribute',
            name='is_jd_logistics',
            field=models.BooleanField(default=False, verbose_name='是否京东物流'),
        ),
        migrations.AlterField(
            model_name='caseattribute',
            name='is_jd_self_manage',
            field=models.BooleanField(default=False, verbose_name='是否京东自营'),
        ),
        migrations.AlterField(
            model_name='caseattribute',
            name='is_jd_supermarket',
            field=models.BooleanField(default=False, verbose_name='是否京东超市'),
        ),
        migrations.AlterField(
            model_name='caseattribute',
            name='is_jd_tianmao_store',
            field=models.BooleanField(default=False, verbose_name='是否天猫商城商品'),
        ),
        migrations.AlterField(
            model_name='caseattribute',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='casecomments',
            name='comment_people',
            field=models.CharField(max_length=20, verbose_name='评论人'),
        ),
        migrations.AlterField(
            model_name='casecomments',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='casecomments',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='casedetailinfos',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='casedetailinfos',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='caseinfos',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='caseinfos',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='caserotioncard',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='caserotioncard',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='stepflow',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='stepflow',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='storeinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='storeinfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
