# Generated by Django 2.2.4 on 2020-12-02 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201201_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_account',
        ),
    ]
