# Generated by Django 2.2.4 on 2020-11-27 03:17

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformations',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('contact_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='联系方式id')),
                ('contact_name', models.CharField(max_length=100, null=True, verbose_name='联系人姓名')),
                ('wechat', models.CharField(max_length=20, null=True, verbose_name='联系人微信号')),
                ('qq', models.CharField(max_length=11, null=True, verbose_name='联系人qq')),
                ('telephone', models.CharField(max_length=11, unique=True, verbose_name='联系人手机号')),
                ('spare_telephone', models.CharField(max_length=11, null=True, verbose_name='联系人备用手机号')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='联系人邮箱')),
            ],
            options={
                'db_table': 'dz_contact_informations',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('order_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='订单id')),
                ('store_platform', models.CharField(max_length=50, verbose_name='店铺平台')),
                ('store_style', models.CharField(max_length=50, verbose_name='店铺风格')),
                ('pay_method', models.SmallIntegerField(choices=[(1, '货到付款'), (2, '微信支付'), (3, '支付宝')], default=3, verbose_name='支付方式')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单总价')),
                ('Deposit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订金金额')),
                ('Balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='尾款金额')),
                ('order_status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '待联系'), (3, '待设计'), (4, '待验货'), (5, '待余款'), (6, '待评价'), (7, '已完成')], default=1, verbose_name='订单状态')),
                ('design_cycle', models.CharField(max_length=20, verbose_name='订单周期')),
                ('design_requirement', tinymce.models.HTMLField(verbose_name='设计要求')),
                ('trade_no', models.CharField(max_length=128, verbose_name='支付编号')),
                ('Store_account', models.CharField(max_length=20, verbose_name='用户店铺账号')),
                ('Store_password', models.CharField(max_length=20, verbose_name='用户店铺密码')),
                ('comment', models.CharField(max_length=256, verbose_name='订单评论')),
            ],
            options={
                'db_table': 'dz_order_info',
            },
        ),
    ]
